version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/golfclub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: daniel1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: golfclub
      MYSQL_ROOT_PASSWORD: daniel1234
    ports:
      - "3306:3306"
